import Head from 'next/head';
import Layout from '../components/layout/main'
import Titlepage from '../components/UI/TitlePage';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix Malika </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Layout />
      </main>
    </div>
  )
}
